import type { ExerciseDef } from './types';

/** Curated bank: expand or edit freely */
export const EXERCISES: ExerciseDef[] = [
  // Upper — compound
  {
    id: 'bb-bench',
    name: 'Barbell bench press',
    focusTags: ['upper', 'total', 'arms'],
    requires: ['barbell', 'bench'],
    loadTypes: ['weights', 'combination'],
    slotMinutes: 8,
    gymPreferred: true,
    defaultOutput: 'reps',
    reps: { sets: 4, reps: '6–10' },
  },
  {
    id: 'db-bench',
    name: 'Dumbbell bench press',
    focusTags: ['upper', 'total', 'arms'],
    requires: ['dumbbells', 'bench'],
    loadTypes: ['weights', 'combination'],
    slotMinutes: 7,
    gymPreferred: false,
    defaultOutput: 'reps',
    reps: { sets: 3, reps: '8–12' },
  },
  {
    id: 'ohp',
    name: 'Overhead press',
    focusTags: ['upper', 'arms', 'total'],
    requires: ['barbell'],
    loadTypes: ['weights', 'combination'],
    slotMinutes: 7,
    gymPreferred: true,
    defaultOutput: 'reps',
    reps: { sets: 4, reps: '6–10' },
  },
  {
    id: 'db-shoulder-press',
    name: 'Dumbbell shoulder press',
    focusTags: ['upper', 'arms', 'total'],
    requires: ['dumbbells'],
    loadTypes: ['weights', 'combination'],
    slotMinutes: 6,
    gymPreferred: false,
    defaultOutput: 'reps',
    reps: { sets: 3, reps: '8–12' },
  },
  {
    id: 'lat-pulldown',
    name: 'Lat pulldown',
    focusTags: ['upper', 'arms', 'total'],
    requires: ['cable'],
    loadTypes: ['weights', 'combination'],
    slotMinutes: 6,
    gymPreferred: true,
    defaultOutput: 'reps',
    reps: { sets: 3, reps: '10–12' },
  },
  {
    id: 'cable-row',
    name: 'Seated cable row',
    focusTags: ['upper', 'total'],
    requires: ['cable'],
    loadTypes: ['weights', 'combination'],
    slotMinutes: 6,
    gymPreferred: true,
    defaultOutput: 'reps',
    reps: { sets: 3, reps: '10–12' },
  },
  {
    id: 'pullup',
    name: 'Pull-up / chin-up',
    focusTags: ['upper', 'arms', 'total'],
    requires: ['pullup_bar'],
    loadTypes: ['bodyweight', 'combination'],
    slotMinutes: 6,
    gymPreferred: false,
    defaultOutput: 'reps',
    reps: { sets: 3, reps: 'AMRAP per set', note: 'Add weight or band assist as needed' },
    rpeTarget: 'RPE 8–9 (leave ~1 rep in reserve)',
    effort: 'secondary',
  },
  {
    id: 'inverted-row',
    name: 'Inverted row',
    focusTags: ['upper', 'arms', 'total'],
    requires: ['none'],
    loadTypes: ['bodyweight', 'combination'],
    slotMinutes: 5,
    gymPreferred: false,
    defaultOutput: 'reps',
    reps: { sets: 3, reps: '8–15' },
  },
  {
    id: 'pushup',
    name: 'Push-up',
    focusTags: ['upper', 'arms', 'total', 'core'],
    requires: ['none'],
    loadTypes: ['bodyweight', 'combination'],
    slotMinutes: 5,
    gymPreferred: false,
    defaultOutput: 'reps',
    reps: { sets: 3, reps: '12–20' },
  },
  {
    id: 'dip',
    name: 'Parallel bar dip',
    focusTags: ['upper', 'arms'],
    requires: ['none'],
    loadTypes: ['bodyweight', 'combination'],
    slotMinutes: 5,
    gymPreferred: true,
    defaultOutput: 'reps',
    reps: { sets: 3, reps: '8–15' },
  },
  // Arms
  {
    id: 'db-curl',
    name: 'Dumbbell curl',
    focusTags: ['arms', 'upper'],
    requires: ['dumbbells'],
    loadTypes: ['weights', 'combination'],
    slotMinutes: 5,
    gymPreferred: false,
    defaultOutput: 'reps',
    reps: { sets: 3, reps: '10–15' },
  },
  {
    id: 'hammer-curl',
    name: 'Hammer curl',
    focusTags: ['arms', 'upper'],
    requires: ['dumbbells'],
    loadTypes: ['weights', 'combination'],
    slotMinutes: 5,
    gymPreferred: false,
    defaultOutput: 'reps',
    reps: { sets: 3, reps: '10–15' },
  },
  {
    id: 'tricep-pushdown',
    name: 'Tricep pushdown',
    focusTags: ['arms', 'upper'],
    requires: ['cable'],
    loadTypes: ['weights', 'combination'],
    slotMinutes: 5,
    gymPreferred: true,
    defaultOutput: 'reps',
    reps: { sets: 3, reps: '12–15' },
  },
  {
    id: 'oh-tricep-ext',
    name: 'Overhead tricep extension',
    focusTags: ['arms', 'upper'],
    requires: ['dumbbells'],
    loadTypes: ['weights', 'combination'],
    slotMinutes: 5,
    gymPreferred: false,
    defaultOutput: 'reps',
    reps: { sets: 3, reps: '10–12' },
  },
  {
    id: 'skullcrusher',
    name: 'Skull crusher',
    focusTags: ['arms', 'upper'],
    requires: ['barbell', 'bench'],
    loadTypes: ['weights', 'combination'],
    slotMinutes: 6,
    gymPreferred: true,
    defaultOutput: 'reps',
    reps: { sets: 3, reps: '10–12' },
  },
  // Legs
  {
    id: 'back-squat',
    name: 'Back squat',
    focusTags: ['legs', 'total'],
    requires: ['barbell'],
    loadTypes: ['weights', 'combination'],
    slotMinutes: 8,
    gymPreferred: true,
    defaultOutput: 'reps',
    reps: { sets: 4, reps: '5–8' },
  },
  {
    id: 'goblet-squat',
    name: 'Goblet squat',
    focusTags: ['legs', 'total'],
    requires: ['dumbbells'],
    loadTypes: ['weights', 'combination'],
    slotMinutes: 6,
    gymPreferred: false,
    defaultOutput: 'reps',
    reps: { sets: 3, reps: '10–15' },
  },
  {
    id: 'rdl',
    name: 'Romanian deadlift',
    focusTags: ['legs', 'total'],
    requires: ['barbell'],
    loadTypes: ['weights', 'combination'],
    slotMinutes: 7,
    gymPreferred: true,
    defaultOutput: 'reps',
    reps: { sets: 3, reps: '8–12' },
  },
  {
    id: 'db-rdl',
    name: 'Dumbbell RDL',
    focusTags: ['legs', 'total'],
    requires: ['dumbbells'],
    loadTypes: ['weights', 'combination'],
    slotMinutes: 6,
    gymPreferred: false,
    defaultOutput: 'reps',
    reps: { sets: 3, reps: '10–12' },
  },
  {
    id: 'leg-press',
    name: 'Leg press',
    focusTags: ['legs', 'total'],
    requires: ['machines'],
    loadTypes: ['weights', 'combination'],
    slotMinutes: 7,
    gymPreferred: true,
    defaultOutput: 'reps',
    reps: { sets: 4, reps: '10–15' },
  },
  {
    id: 'lunge',
    name: 'Walking lunge',
    focusTags: ['legs', 'total'],
    requires: ['none'],
    loadTypes: ['bodyweight', 'combination'],
    slotMinutes: 6,
    gymPreferred: false,
    defaultOutput: 'reps',
    reps: { sets: 3, reps: '10–12 / leg' },
  },
  {
    id: 'bulgarian-split',
    name: 'Bulgarian split squat',
    focusTags: ['legs', 'total'],
    requires: ['bench'],
    loadTypes: ['weights', 'bodyweight', 'combination'],
    slotMinutes: 7,
    gymPreferred: false,
    defaultOutput: 'reps',
    reps: { sets: 3, reps: '8–12 / leg' },
  },
  {
    id: 'calf-raise',
    name: 'Standing calf raise',
    focusTags: ['legs', 'total'],
    requires: ['none'],
    loadTypes: ['bodyweight', 'weights', 'combination'],
    slotMinutes: 4,
    gymPreferred: false,
    defaultOutput: 'reps',
    reps: { sets: 3, reps: '15–20' },
  },
  {
    id: 'kb-swing',
    name: 'Kettlebell swing',
    focusTags: ['legs', 'total', 'core'],
    requires: ['kettlebell'],
    loadTypes: ['weights', 'combination'],
    slotMinutes: 6,
    gymPreferred: false,
    defaultOutput: 'reps',
    reps: { sets: 4, reps: '15–20' },
  },
  // Core
  {
    id: 'plank',
    name: 'Front plank',
    focusTags: ['core', 'total'],
    requires: ['none'],
    loadTypes: ['bodyweight', 'combination'],
    slotMinutes: 4,
    gymPreferred: false,
    defaultOutput: 'time',
    time: { sets: 3, secondsPerSet: 45 },
  },
  {
    id: 'side-plank',
    name: 'Side plank',
    focusTags: ['core', 'total'],
    requires: ['none'],
    loadTypes: ['bodyweight', 'combination'],
    slotMinutes: 4,
    gymPreferred: false,
    defaultOutput: 'time',
    time: { sets: 2, secondsPerSet: 30, note: 'each side' },
  },
  {
    id: 'dead-bug',
    name: 'Dead bug',
    focusTags: ['core', 'total'],
    requires: ['none'],
    loadTypes: ['bodyweight', 'combination'],
    slotMinutes: 4,
    gymPreferred: false,
    defaultOutput: 'reps',
    reps: { sets: 3, reps: '10–12 / side' },
  },
  {
    id: 'pallof',
    name: 'Pallof press',
    focusTags: ['core', 'total'],
    requires: ['cable'],
    loadTypes: ['weights', 'combination'],
    slotMinutes: 5,
    gymPreferred: true,
    defaultOutput: 'reps',
    reps: { sets: 3, reps: '12–15 / side' },
  },
  {
    id: 'cable-crunch',
    name: 'Cable crunch',
    focusTags: ['core'],
    requires: ['cable'],
    loadTypes: ['weights', 'combination'],
    slotMinutes: 5,
    gymPreferred: true,
    defaultOutput: 'reps',
    reps: { sets: 3, reps: '12–20' },
  },
  {
    id: 'hanging-knee',
    name: 'Hanging knee raise',
    focusTags: ['core', 'arms'],
    requires: ['pullup_bar'],
    loadTypes: ['bodyweight', 'combination'],
    slotMinutes: 5,
    gymPreferred: false,
    defaultOutput: 'reps',
    reps: { sets: 3, reps: '10–15' },
  },
  {
    id: 'band-pulldown-abs',
    name: 'Band crunch / kneeling crunch',
    focusTags: ['core'],
    requires: ['bands'],
    loadTypes: ['weights', 'bodyweight', 'combination'],
    slotMinutes: 4,
    gymPreferred: false,
    defaultOutput: 'reps',
    reps: { sets: 3, reps: '15–20' },
  },
];
