/**
 * Form tutorials (YouTube). Swap URLs anytime; keyed by exercise `id` in exerciseBank.
 */
export const EXERCISE_VIDEO_BY_ID: Record<string, string> = {
  'bb-bench': 'https://www.youtube.com/watch?v=vcBig73ojpE',
  'db-bench': 'https://www.youtube.com/watch?v=Y_7aHqXeCfQ',
  ohp: 'https://www.youtube.com/watch?v=k4WoLZbonns',
  'db-shoulder-press': 'https://www.youtube.com/watch?v=JzGZqTXqhqY',
  'lat-pulldown': 'https://www.youtube.com/watch?v=SALxEARiMkw',
  'cable-row': 'https://www.youtube.com/watch?v=7BkgqzC6WsM',
  pullup: 'https://www.youtube.com/watch?v=eGo4IYlbE5k',
  'inverted-row': 'https://www.youtube.com/watch?v=GdyhjXlxE-U',
  pushup: 'https://www.youtube.com/watch?v=IODxDxX7oi4',
  dip: 'https://www.youtube.com/watch?v=2z8JmcrW-As',
  'db-curl': 'https://www.youtube.com/watch?v=ykJmrZ5v0Ng',
  'hammer-curl': 'https://www.youtube.com/watch?v=zC3isgCsB4E',
  'tricep-pushdown': 'https://www.youtube.com/watch?v=6Fzep104f0s',
  'oh-tricep-ext': 'https://www.youtube.com/watch?v=nRiJVZDpdL0',
  skullcrusher: 'https://www.youtube.com/watch?v=d_KZxkY_0cM',
  'back-squat': 'https://www.youtube.com/watch?v=bs_Ej32IYgo',
  'goblet-squat': 'https://www.youtube.com/watch?v=0eW8av1WC4g',
  rdl: 'https://www.youtube.com/watch?v=_oyxCn2iSjU',
  'db-rdl': 'https://www.youtube.com/watch?v=b_I2JvWLaQs',
  'leg-press': 'https://www.youtube.com/watch?v=sOwpMjEkkYA',
  lunge: 'https://www.youtube.com/watch?v=wrwwXE_x-pQ',
  'bulgarian-split': 'https://www.youtube.com/watch?v=2C-uNgKwPLE',
  'calf-raise': 'https://www.youtube.com/watch?v=-M4-G8p8fmc',
  'kb-swing': 'https://www.youtube.com/watch?v=6sulElSJarQ',
  plank: 'https://www.youtube.com/watch?v=pSHjTRCQxIw',
  'side-plank': 'https://www.youtube.com/watch?v=wqzrb67Dwf8',
  'dead-bug': 'https://www.youtube.com/watch?v=g_BYB0RkMj8',
  pallof: 'https://www.youtube.com/watch?v=AH_QZLm_0-0',
  'cable-crunch': 'https://www.youtube.com/watch?v=2RPTvogFfRU',
  'hanging-knee': 'https://www.youtube.com/watch?v=pV1cCIjqgn0',
  'band-pulldown-abs': 'https://www.youtube.com/watch?v=vD2SBd0pr0E',
};
